version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongo_gestion_proyectos
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: gestion-proyectos
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
